# reads SDL2_SUPPORT_LIBS_REQUIRED

# will set 
# SDL2_INCLUDE_DIR

SET(SDL2_SEARCH_PATHS
	/usr/lib/x86_64-linux-gnu
	/use/lib/
)

FIND_PATH(SDL2_INCLUDE_DIR 
	NAMES SDL.h
	HINTS $ENV{SDL2DIR} /usr/include/SDL2
	PATH_SUFFIXES include/SDL2 include
	PATHS ${SDL2_SEARCH_PATHS}
)

FIND_LIBRARY(SDL2_SUPPORT_LIBRARIES
	NAMES SDL2_ttf SDL2_image
	HINTS $ENV{SDL2DIR}
	PATH_SUFFIXES lib64 lib x86_64-linux-gnu
	PATHS ${SDL2_SEARCH_PATHS}
)

INCLUDE(FindPackageHandleStandardArgs)

FIND_PACKAGE_HANDLE_STANDARD_ARGS(REQUIRED_VARS SDL2_SUPPORT_LIBRARIES SDL2_INCLUDE_DIR)
